import assert from "node:assert/strict";
import { chmod, mkdir, mkdtemp, readdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { codexAuthPath, loadCodexAuth } from "../lib/codex-auth.js";
import { buildImageRequestBody, decodeChatGptAccountId, extractImageFromEvents, saveImagePng } from "../lib/image.js";
import { spawnWithInput } from "../lib/runners.js";
import { loadSession, saveSession, workspaceKey } from "../lib/state.js";
import { collectHandoff, parseTranscriptJsonl, serializeClaudeTranscript } from "../lib/transcript.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CF = path.join(ROOT, "bin", "cf.mjs");

async function withTempDir(fn) {
  const dir = await mkdtemp(path.join(os.tmpdir(), "cf-cc-test-"));
  try {
    return await fn(dir);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

// --- Transcript serialization (the CC handoff) ----------------------------

function userEntry(content, extra = {}) {
  return { type: "user", message: { role: "user", content }, isSidechain: false, ...extra };
}

function assistantEntry(content, extra = {}) {
  return { type: "assistant", message: { role: "assistant", content }, isSidechain: false, ...extra };
}

test("serializeClaudeTranscript keeps chronological order with role labels and tool calls", () => {
  const entries = [
    userEntry("first question"),
    assistantEntry([{ type: "thinking", thinking: "private reasoning" }, { type: "text", text: "First reply" }]),
    userEntry("second question"),
    assistantEntry([{ type: "text", text: "Second reply" }, { type: "tool_use", id: "t1", name: "Read", input: { file_path: "a.ts" } }]),
  ];
  const text = serializeClaudeTranscript(entries, { maxBytes: 10000 });
  assert.match(text, /User:\nfirst question/);
  assert.match(text, /Lead:\nFirst reply/);
  assert.match(text, /→ Read\(/);
  assert.ok(text.indexOf("first question") < text.indexOf("second question"), "chronological order");
  assert.doesNotMatch(text, /private reasoning/);
});

test("serializeClaudeTranscript labels tool results via the tool_use map and skips noise", () => {
  const entries = [
    assistantEntry([{ type: "tool_use", id: "t1", name: "Bash", input: { command: "ls" } }]),
    userEntry([{ type: "tool_result", tool_use_id: "t1", content: "file-a\nfile-b" }]),
    { type: "user", message: { role: "user", content: "<command-name>/clear</command-name>" }, isSidechain: false },
    { type: "user", message: { role: "user", content: "Caveat: The messages below were generated by the user while running local commands." }, isSidechain: false },
    { type: "user", message: { role: "user", content: "meta note" }, isMeta: true, isSidechain: false },
    { type: "user", message: { role: "user", content: "from a subagent" }, isSidechain: true },
    { type: "file-history-snapshot", snapshot: {} },
    { type: "system", subtype: "local_command", content: "ran /clear" },
    userEntry("real question"),
  ];
  const text = serializeClaudeTranscript(entries);
  assert.match(text, /Tool result Bash:\nfile-a/);
  assert.match(text, /User:\nreal question/);
  assert.doesNotMatch(text, /command-name/);
  assert.doesNotMatch(text, /Caveat: The messages below/);
  assert.doesNotMatch(text, /meta note/);
  assert.doesNotMatch(text, /from a subagent/);
  assert.doesNotMatch(text, /ran \/clear/);
});

test("serializeClaudeTranscript keeps ConsensFlow run results near-whole (cross-pollination)", () => {
  const reply = "A".repeat(5000);
  const entries = [
    assistantEntry([{ type: "tool_use", id: "t1", name: "Bash", input: { command: 'node "/plug/bin/cf.mjs" run @iris --prompt-file "/ws/.consensflow-cc/pending-prompt.md"' } }]),
    userEntry([{ type: "tool_result", tool_use_id: "t1", content: reply }]),
    assistantEntry([{ type: "tool_use", id: "t2", name: "Read", input: { file_path: "a.ts" } }]),
    userEntry([{ type: "tool_result", tool_use_id: "t2", content: reply }]),
  ];
  const text = serializeClaudeTranscript(entries);
  // The consultation survives beyond the generic cap; ordinary tool results stay tightly truncated.
  assert.match(text, /Tool result consensflow run \(@iris\):/);
  assert.ok(text.includes(reply), "cf run reply kept near-whole");
  assert.match(text, /Tool result Read:\nA{1500}…\[truncated\]/);
});

test("serializeClaudeTranscript honors compaction and summary entries", () => {
  const entries = [
    { type: "summary", summary: "session about cache design", leafUuid: "x" },
    userEntry("compacted away question", { isCompactSummary: true, message: { role: "user", content: "the earlier stuff" } }),
    userEntry("kept question"),
  ];
  const text = serializeClaudeTranscript(entries);
  assert.match(text, /\[Session summary\]\nsession about cache design/);
  assert.match(text, /\[Earlier conversation summary\]\nthe earlier stuff/);
  assert.match(text, /User:\nkept question/);
});

test("serializeClaudeTranscript caps bytes keeping the tail, and handles empty input", () => {
  const long = Array.from({ length: 50 }, () => userEntry("x".repeat(500)));
  const text = serializeClaudeTranscript(long, { maxBytes: 2000 });
  assert.ok(Buffer.byteLength(text, "utf8") <= 2000);
  assert.match(text, /\[earlier handoff truncated\]/);
  assert.equal(serializeClaudeTranscript([]), "");
  assert.equal(serializeClaudeTranscript(null), "");
});

test("parseTranscriptJsonl tolerates garbage lines and collectHandoff degrades to empty", async () => {
  const entries = parseTranscriptJsonl(`{"type":"user","message":{"role":"user","content":"hi"}}\nnot json\n\n{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"yo"}]}}`);
  assert.equal(entries.length, 2);
  await withTempDir(async (dir) => {
    // No session stash at all -> empty handoff, no throw.
    assert.equal(await collectHandoff(dir), "");
    // Stash pointing at a missing transcript -> still empty, no throw.
    await saveSession(dir, { transcriptPath: path.join(dir, "missing.jsonl") });
    assert.equal(await collectHandoff(dir), "");
    // Real transcript -> serialized handoff.
    const transcriptPath = path.join(dir, "t.jsonl");
    await writeFile(transcriptPath, `${JSON.stringify({ type: "user", message: { role: "user", content: "let's design the cache" }, isSidechain: false })}\n`, "utf8");
    await saveSession(dir, { transcriptPath });
    assert.match(await collectHandoff(dir), /User:\nlet's design the cache/);
  });
});

// --- Hook scripts ----------------------------------------------------------

function hookEnv(dir, extra = {}) {
  return { CONSENSFLOW_HOME: path.join(dir, "home"), ...extra };
}

async function runHook(script, payload, env) {
  return await spawnWithInput(process.execPath, [path.join(ROOT, "scripts", script)], {
    input: JSON.stringify(payload),
    env,
    timeoutMs: 15000,
  });
}

async function addParticipant(dir, preset, env = {}) {
  const result = await spawnWithInput(process.execPath, [CF, "participants", "add", preset], {
    cwd: dir,
    env: hookEnv(dir, env),
    timeoutMs: 15000,
  });
  assert.equal(result.exitCode, 0, result.stderr);
}

test("session-start hook stashes the transcript path and emits a roster context", async () => {
  await withTempDir(async (dir) => {
    await addParticipant(dir, "zeus");
    const result = await runHook("session-start-hook.mjs", { cwd: dir, session_id: "s-1", transcript_path: "/tmp/tr.jsonl", source: "startup" }, hookEnv(dir));
    assert.equal(result.exitCode, 0);
    assert.match(result.stdout, /ConsensFlow is available/);
    assert.match(result.stdout, /@zeus \(claude-code claude-opus-4-8\)/);
    assert.match(result.stdout, /never apply a participant's advice/);
    assert.match(result.stdout, /bin\/cf\.mjs/);
    const oldHome = process.env.CONSENSFLOW_HOME;
    process.env.CONSENSFLOW_HOME = path.join(dir, "home");
    try {
      const session = await loadSession(dir);
      assert.equal(session.sessionId, "s-1");
      assert.equal(session.transcriptPath, "/tmp/tr.jsonl");
    } finally {
      if (oldHome === undefined) delete process.env.CONSENSFLOW_HOME;
      else process.env.CONSENSFLOW_HOME = oldHome;
    }
  });
});

test("user-prompt hook routes a configured @mention to a run instruction with a stashed prompt file", async () => {
  await withTempDir(async (dir) => {
    await addParticipant(dir, "zeus");
    const result = await runHook("user-prompt-hook.mjs", { cwd: dir, session_id: "s-1", transcript_path: "/tmp/tr.jsonl", prompt: "@zeus what about the cache?" }, hookEnv(dir));
    assert.equal(result.exitCode, 0);
    const output = JSON.parse(result.stdout);
    const context = output.hookSpecificOutput.additionalContext;
    assert.equal(output.hookSpecificOutput.hookEventName, "UserPromptSubmit");
    assert.match(context, /addresses the participant @zeus/);
    assert.match(context, /run @zeus --prompt-file/);
    assert.match(context, /without the user's approval/);
    // The stash lives under the config home, keyed by workspace — never inside the project.
    const promptFile = context.match(/--prompt-file "([^"]+)"/)[1];
    assert.equal(promptFile, path.join(dir, "home", "consensflow-cc", "workspaces", workspaceKey(dir), "pending-prompt.md"));
    assert.equal(await readFile(promptFile, "utf8"), "what about the cache?");
  });
});

test("user-prompt hook stays silent for stray mentions, commands, and unknown names", async () => {
  await withTempDir(async (dir) => {
    await addParticipant(dir, "zeus");
    for (const prompt of ["install @types/node please", "/cf status", "just fix the bug", "@ghost are you there?"]) {
      const result = await runHook("user-prompt-hook.mjs", { cwd: dir, prompt }, hookEnv(dir));
      assert.equal(result.exitCode, 0, prompt);
      assert.equal(result.stdout.trim(), "", `expected silence for: ${prompt}`);
    }
  });
});

test("user-prompt hook surfaces the one-at-a-time rule for multiple leading mentions", async () => {
  await withTempDir(async (dir) => {
    await addParticipant(dir, "zeus");
    await addParticipant(dir, "athena");
    const result = await runHook("user-prompt-hook.mjs", { cwd: dir, prompt: "@zeus @athena what do you both think?" }, hookEnv(dir));
    assert.equal(result.exitCode, 0);
    const context = JSON.parse(result.stdout).hookSpecificOutput.additionalContext;
    assert.match(context, /one participant at a time/);
    assert.match(context, /do not fan out/);
  });
});

test("hooks bail out silently inside participant subprocesses (CONSENSFLOW_CHILD)", async () => {
  await withTempDir(async (dir) => {
    await addParticipant(dir, "zeus");
    for (const script of ["session-start-hook.mjs", "user-prompt-hook.mjs"]) {
      const result = await runHook(script, { cwd: dir, session_id: "child", transcript_path: "/tmp/child.jsonl", prompt: "@zeus hi" }, hookEnv(dir, { CONSENSFLOW_CHILD: "1" }));
      assert.equal(result.exitCode, 0, script);
      assert.equal(result.stdout.trim(), "", `${script} must not emit context in a child`);
    }
    // And the stash was never written by those child invocations.
    const oldHome = process.env.CONSENSFLOW_HOME;
    process.env.CONSENSFLOW_HOME = path.join(dir, "home");
    try {
      assert.equal((await loadSession(dir)).sessionId, undefined);
    } finally {
      if (oldHome === undefined) delete process.env.CONSENSFLOW_HOME;
      else process.env.CONSENSFLOW_HOME = oldHome;
    }
  });
});

// --- CLI end-to-end with fake engine binaries -------------------------------
// Per project policy, live agent CLIs are never invoked from tests. Each engine gets a PATH shim
// that dumps its argv/env/stdin to a file and prints engine-shaped output, so the full spawn →
// packet → parse → artifact path is exercised for all four engines.

const SHIM_BODIES = {
  claude: `console.log(JSON.stringify({ type: "result", result: "CLAUDE OK" }));`,
  codex: `console.log(JSON.stringify({ type: "thread.started", thread_id: "t" }));\nconsole.log(JSON.stringify({ type: "item.completed", item: { type: "agent_message", text: "CODEX OK" } }));`,
  pi: `console.log(JSON.stringify({ type: "agent_end", messages: [{ role: "assistant", content: [{ type: "text", text: "PI OK" }] }] }));`,
  opencode: `console.log(JSON.stringify({ text: "OPENCODE OK" }));`,
};

async function makeFakeEngines(dir) {
  const bin = path.join(dir, "fakebin");
  const out = path.join(dir, "engine-out");
  await mkdir(bin, { recursive: true });
  await mkdir(out, { recursive: true });
  for (const [name, body] of Object.entries(SHIM_BODIES)) {
    const source = [
      "#!/usr/bin/env node",
      'const fs = require("node:fs");',
      'const path = require("node:path");',
      'let stdin = "";',
      'try { stdin = fs.readFileSync(0, "utf8"); } catch {}',
      "let packetFromFile = null;",
      'const fileIdx = process.argv.indexOf("--file");',
      'if (fileIdx >= 0) { try { packetFromFile = fs.readFileSync(process.argv[fileIdx + 1], "utf8"); } catch {} }',
      "const dump = {",
      `  name: ${JSON.stringify(name)},`,
      "  argv: process.argv.slice(2),",
      "  stdin,",
      "  packetFromFile,",
      "  env: {",
      "    CONSENSFLOW_CHILD: process.env.CONSENSFLOW_CHILD ?? null,",
      "    OPENCODE_PERMISSION: process.env.OPENCODE_PERMISSION ?? null,",
      "    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY ?? null,",
      "    OPENAI_API_KEY: process.env.OPENAI_API_KEY ?? null,",
      "  },",
      "};",
      `fs.writeFileSync(path.join(process.env.FAKE_ENGINE_OUT, ${JSON.stringify(name)} + ".json"), JSON.stringify(dump, null, 2));`,
      body,
    ].join("\n");
    const shimPath = path.join(bin, name);
    await writeFile(shimPath, source, "utf8");
    await chmod(shimPath, 0o755);
  }
  return { bin, out };
}

async function runCf(args, { ws, dir, fake }, extraEnv = {}) {
  return await spawnWithInput(process.execPath, [CF, ...args], {
    cwd: ws,
    timeoutMs: 30000,
    env: {
      CONSENSFLOW_HOME: path.join(dir, "home"),
      PATH: `${fake.bin}${path.delimiter}${process.env.PATH}`,
      FAKE_ENGINE_OUT: fake.out,
      // Billing guard probe: these must NOT reach claude/codex children.
      ANTHROPIC_API_KEY: "leak-test",
      OPENAI_API_KEY: "leak-test",
      ...extraEnv,
    },
  });
}

async function latestPacket(ws, dir) {
  const current = JSON.parse(await readFile(path.join(dir, "home", "consensflow-cc", "workspaces", workspaceKey(ws), "current.json"), "utf8"));
  return {
    current,
    packet: await readFile(path.join(current.latestRunDir, "packet.md"), "utf8"),
    result: JSON.parse(await readFile(path.join(current.latestRunDir, "result.json"), "utf8")),
  };
}

test("e2e: all four engines run, parse, and persist artifacts through the real spawn path", async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, "ws");
    await mkdir(ws, { recursive: true });
    const fake = await makeFakeEngines(dir);
    const ctx = { ws, dir, fake };
    for (const preset of ["zeus", "athena", "iris", "luna"]) {
      const add = await runCf(["participants", "add", preset], ctx);
      assert.equal(add.exitCode, 0, add.stderr);
    }

    const cases = [
      { ref: "@zeus", engine: "claude", expect: "CLAUDE OK" },
      { ref: "@athena", engine: "codex", expect: "CODEX OK" },
      { ref: "@iris", engine: "pi", expect: "PI OK" },
      { ref: "@luna", engine: "opencode", expect: "OPENCODE OK" },
    ];
    for (const { ref, engine, expect } of cases) {
      const run = await runCf(["run", ref, "ping", "from", "the", "test"], ctx);
      assert.equal(run.exitCode, 0, `${ref}: ${run.stderr}`);
      assert.match(run.stdout, new RegExp(`# ${ref}`), `${ref}: header`);
      assert.ok(run.stdout.includes(expect), `${ref}: parsed engine output`);
      assert.match(run.stdout, /get their approval before applying/, `${ref}: consent reminder`);

      const { packet, result } = await latestPacket(ws, dir);
      assert.match(packet, /# ConsensFlow Packet/);
      assert.match(packet, /Read-only: you can inspect the workspace/);
      assert.match(packet, /ping from the test/);
      assert.equal(result.output, expect);
      assert.equal(result.exitCode, 0);

      const dump = JSON.parse(await readFile(path.join(fake.out, `${engine}.json`), "utf8"));
      assert.equal(dump.env.CONSENSFLOW_CHILD, "1", `${engine}: child marker reaches the subprocess`);
      const packetSeen = engine === "opencode" ? dump.packetFromFile : dump.stdin;
      assert.ok(String(packetSeen ?? "").includes("# ConsensFlow Packet"), `${engine}: packet delivered`);
    }

    // The relocation contract: a run never creates anything inside the project workspace.
    assert.ok(!(await readdir(ws)).some((entry) => entry.startsWith(".consensflow")), "no .consensflow* dir in the workspace");

    // Engine-specific guards observed from inside the children.
    const claude = JSON.parse(await readFile(path.join(fake.out, "claude.json"), "utf8"));
    assert.ok(claude.argv.includes("--bare"), "claude child skips plugin/hook discovery");
    assert.ok(claude.argv.includes("--disallowedTools"), "claude readonly deny list");
    assert.equal(claude.argv[claude.argv.indexOf("--model") + 1], "claude-opus-4-8");
    assert.equal(claude.argv[claude.argv.indexOf("--effort") + 1], "max");
    assert.equal(claude.env.ANTHROPIC_API_KEY, null, "billing guard strips ANTHROPIC_API_KEY");
    const codex = JSON.parse(await readFile(path.join(fake.out, "codex.json"), "utf8"));
    assert.ok(codex.argv.includes("--sandbox"), "codex sandbox flag");
    assert.ok(codex.argv.includes("read-only"), "codex readonly sandbox");
    assert.equal(codex.env.OPENAI_API_KEY, null, "billing guard strips OPENAI_API_KEY");
    const piDump = JSON.parse(await readFile(path.join(fake.out, "pi.json"), "utf8"));
    assert.ok(piDump.argv.includes("--no-extensions"), "pi child runs without extensions");
    assert.equal(piDump.argv[piDump.argv.indexOf("--thinking") + 1], "xhigh");
    const opencode = JSON.parse(await readFile(path.join(fake.out, "opencode.json"), "utf8"));
    assert.deepEqual(JSON.parse(opencode.env.OPENCODE_PERMISSION), { edit: "deny", bash: "deny" });
  });
});

test("e2e: the handoff from the session stash reaches the packet", async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, "ws");
    await mkdir(ws, { recursive: true });
    const fake = await makeFakeEngines(dir);
    const ctx = { ws, dir, fake };
    assert.equal((await runCf(["participants", "add", "zeus"], ctx)).exitCode, 0);

    // First run: no session stash -> no handoff section.
    assert.equal((await runCf(["run", "@zeus", "first", "question"], ctx)).exitCode, 0);
    assert.doesNotMatch((await latestPacket(ws, dir)).packet, /## Handoff — current session/);

    // Stash a transcript like the hooks would, then run again.
    const transcriptPath = path.join(dir, "session.jsonl");
    await writeFile(
      transcriptPath,
      [
        JSON.stringify({ type: "user", message: { role: "user", content: "let's design the cache" }, isSidechain: false }),
        JSON.stringify({ type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "I propose write-through" }] }, isSidechain: false }),
      ].join("\n"),
      "utf8",
    );
    const oldHome = process.env.CONSENSFLOW_HOME;
    process.env.CONSENSFLOW_HOME = path.join(dir, "home");
    try {
      await saveSession(ws, { sessionId: "s-1", transcriptPath });
    } finally {
      if (oldHome === undefined) delete process.env.CONSENSFLOW_HOME;
      else process.env.CONSENSFLOW_HOME = oldHome;
    }
    assert.equal((await runCf(["run", "@zeus", "second", "question"], ctx)).exitCode, 0);
    const { packet } = await latestPacket(ws, dir);
    assert.match(packet, /## Handoff — current session/);
    assert.match(packet, /User:\nlet's design the cache/);
    assert.match(packet, /Lead:\nI propose write-through/);
    // And --no-handoff suppresses it again.
    assert.equal((await runCf(["run", "@zeus", "third", "--no-handoff"], ctx)).exitCode, 0);
    assert.doesNotMatch((await latestPacket(ws, dir)).packet, /## Handoff — current session/);
  });
});

test("e2e: nested runs are refused and unknown participants error cleanly", async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, "ws");
    await mkdir(ws, { recursive: true });
    const fake = await makeFakeEngines(dir);
    const ctx = { ws, dir, fake };
    assert.equal((await runCf(["participants", "add", "zeus"], ctx)).exitCode, 0);

    const unknown = await runCf(["run", "@ghost", "hi"], ctx);
    assert.equal(unknown.exitCode, 1);
    assert.match(unknown.stderr, /Unknown participant: @ghost/);
    assert.match(unknown.stderr, /@zeus/);

    const nested = await spawnWithInput(process.execPath, [CF, "run", "@zeus", "hi"], {
      cwd: ws,
      timeoutMs: 15000,
      env: { CONSENSFLOW_HOME: path.join(dir, "home"), CONSENSFLOW_CHILD: "1" },
    });
    assert.equal(nested.exitCode, 1);
    assert.match(nested.stderr, /Nested ConsensFlow runs are disabled/);
  });
});

// --- Image participants (Codex backend) -------------------------------------

function fakeJwt(claims) {
  const payload = Buffer.from(JSON.stringify(claims)).toString("base64url");
  return `header.${payload}.signature`;
}

test("image helpers: JWT account id, request body, SSE extraction, PNG save", async () => {
  // decodeChatGptAccountId pulls the claim out of a ChatGPT OAuth JWT.
  assert.equal(decodeChatGptAccountId(fakeJwt({ "https://api.openai.com/auth": { chatgpt_account_id: "acc_42" } })), "acc_42");
  assert.throws(() => decodeChatGptAccountId("not-a-jwt"), /JWT/);

  // buildImageRequestBody triggers exactly one image_generation call with the prompt.
  const body = buildImageRequestBody("a red cat", "gpt-5.5");
  assert.equal(body.model, "gpt-5.5");
  assert.equal(body.tools[0].type, "image_generation");
  assert.equal(body.input[0].content[0].text, "a red cat");

  // extractImageFromEvents finds the base64 image + metadata across SSE events.
  const img = extractImageFromEvents([
    { type: "response.created", response: { id: "r1" } },
    { type: "response.output_item.done", item: { type: "image_generation_call", id: "i1", status: "completed", result: "QkFTRTY0", revised_prompt: "a bright red cat" } },
    { type: "response.completed", response: { id: "r1" } },
  ]);
  assert.equal(img.base64, "QkFTRTY0");
  assert.equal(img.revisedPrompt, "a bright red cat");
  assert.equal(img.responseId, "r1");
  assert.throws(() => extractImageFromEvents([{ type: "error", message: "boom" }]), /boom/);
  assert.throws(() => extractImageFromEvents([{ type: "response.failed", response: { error: { message: "content blocked" } } }]), /content blocked/);
  // A text-only / empty stream yields no image rather than a bogus base64.
  assert.equal(extractImageFromEvents([{ type: "response.output_text.delta", delta: "hi" }]).base64, undefined);
  assert.equal(extractImageFromEvents([]).base64, undefined);

  // saveImagePng decodes base64 and writes the file.
  await withTempDir(async (dir) => {
    const saved = await saveImagePng(Buffer.from("PNGDATA").toString("base64"), path.join(dir, "runs", "img1"), "image.png");
    assert.equal((await readFile(saved)).toString(), "PNGDATA");
  });
});

test("loadCodexAuth reads the Codex CLI login (account_id field, JWT fallback, clear errors)", async () => {
  await withTempDir(async (dir) => {
    const oldCodexHome = process.env.CODEX_HOME;
    process.env.CODEX_HOME = path.join(dir, "codex-home");
    try {
      // No auth file at all → fix-it error naming the path.
      assert.match(codexAuthPath(), /codex-home/);
      await assert.rejects(loadCodexAuth(), /codex login/);

      // access_token + explicit account_id → both returned verbatim.
      await mkdir(process.env.CODEX_HOME, { recursive: true });
      const token = fakeJwt({ "https://api.openai.com/auth": { chatgpt_account_id: "acc_jwt" } });
      await writeFile(path.join(process.env.CODEX_HOME, "auth.json"), JSON.stringify({ tokens: { access_token: token, account_id: "acc_field" } }), "utf8");
      assert.deepEqual(await loadCodexAuth(), { token, accountId: "acc_field" });

      // Missing account_id field → decoded from the JWT claim.
      await writeFile(path.join(process.env.CODEX_HOME, "auth.json"), JSON.stringify({ tokens: { access_token: token } }), "utf8");
      assert.deepEqual(await loadCodexAuth(), { token, accountId: "acc_jwt" });

      // Claim-less access token falls back to the id_token's claim.
      const bare = fakeJwt({ sub: "x" });
      const idToken = fakeJwt({ "https://api.openai.com/auth": { chatgpt_account_id: "acc_id_token" } });
      await writeFile(path.join(process.env.CODEX_HOME, "auth.json"), JSON.stringify({ tokens: { access_token: bare, id_token: idToken } }), "utf8");
      assert.equal((await loadCodexAuth()).accountId, "acc_id_token");

      // API-key-only auth (no ChatGPT tokens) → clear error.
      await writeFile(path.join(process.env.CODEX_HOME, "auth.json"), JSON.stringify({ OPENAI_API_KEY: "sk-test" }), "utf8");
      await assert.rejects(loadCodexAuth(), /no ChatGPT access token/);
    } finally {
      if (oldCodexHome === undefined) delete process.env.CODEX_HOME;
      else process.env.CODEX_HOME = oldCodexHome;
    }
  });
});

test("e2e: @pygmalion without a Codex login errors cleanly before any network call", async () => {
  await withTempDir(async (dir) => {
    const ws = path.join(dir, "ws");
    await mkdir(ws, { recursive: true });
    const fake = await makeFakeEngines(dir);
    const ctx = { ws, dir, fake };
    assert.equal((await runCf(["participants", "add", "pygmalion"], ctx)).exitCode, 0);
    const run = await runCf(["run", "@pygmalion", "a", "minimalist", "logo"], ctx, { CODEX_HOME: path.join(dir, "empty-codex-home") });
    assert.equal(run.exitCode, 1);
    assert.match(run.stderr, /No Codex CLI login found/);
    assert.match(run.stderr, /codex login/);
  });
});

// --- Plugin packaging: consent gate, hooks wiring, import boundaries --------

test("the consent gate and name-neutrality stay locked into the skill, command, and hook sources", async () => {
  const skill = await readFile(path.join(ROOT, "skills", "consensflow", "SKILL.md"), "utf8");
  assert.match(skill, /MUST NOT apply, merge, commit/);
  assert.match(skill, /NO user permission needed/);
  assert.match(skill, /ask freely, apply only with a green light/);
  const command = await readFile(path.join(ROOT, "commands", "cf.md"), "utf8");
  assert.match(command, /do not apply, commit, or keep its output/);
  const promptHook = await readFile(path.join(ROOT, "scripts", "user-prompt-hook.mjs"), "utf8");
  assert.match(promptHook, /without the user's approval/);

  // The personal name must not appear in anything the plugin ships.
  for (const dirName of ["bin", "lib", "scripts", "skills", "commands", "hooks", ".claude-plugin"]) {
    const base = path.join(ROOT, dirName);
    for (const file of await readdir(base, { recursive: true })) {
      const full = path.join(base, file);
      const content = await readFile(full, "utf8").catch(() => "");
      assert.doesNotMatch(content, /Gabriel/, `${dirName}/${file}`);
    }
  }
});

test("hooks.json wires both hooks to scripts that exist, via CLAUDE_PLUGIN_ROOT", async () => {
  const hooks = JSON.parse(await readFile(path.join(ROOT, "hooks", "hooks.json"), "utf8"));
  for (const event of ["SessionStart", "UserPromptSubmit"]) {
    const matchers = hooks.hooks[event];
    assert.ok(Array.isArray(matchers) && matchers.length === 1, `${event} registered once`);
    const command = matchers[0].hooks[0].command;
    assert.match(command, /\$\{CLAUDE_PLUGIN_ROOT\}/);
    const script = command.match(/\$\{CLAUDE_PLUGIN_ROOT\}\/(\S+?\.mjs)/)?.[1];
    assert.ok(script, `${event} command references a script`);
    await readFile(path.join(ROOT, script), "utf8"); // throws if missing
  }
  const manifest = JSON.parse(await readFile(path.join(ROOT, ".claude-plugin", "plugin.json"), "utf8"));
  assert.equal(manifest.name, "consensflow");
});

test("every lib symbol the CLI and hooks import is actually exported (boundary smoke)", async () => {
  const sources = [
    path.join(ROOT, "bin", "cf.mjs"),
    path.join(ROOT, "scripts", "session-start-hook.mjs"),
    path.join(ROOT, "scripts", "user-prompt-hook.mjs"),
  ];
  const importRe = /import\s+\{([^}]+)\}\s+from\s+"(\.\.\/lib\/[^"]+|\.\/hook-io\.mjs)"/g;
  let checked = 0;
  for (const source of sources) {
    const src = await readFile(source, "utf8");
    let match;
    while ((match = importRe.exec(src))) {
      const symbols = match[1].split(",").map((s) => s.trim().split(/\s+as\s+/)[0].trim()).filter(Boolean);
      const target = match[2].startsWith("../lib/")
        ? path.join(ROOT, "lib", path.basename(match[2]))
        : path.join(ROOT, "scripts", "hook-io.mjs");
      const loaded = await import(target);
      for (const symbol of symbols) {
        assert.notEqual(loaded[symbol], undefined, `${match[2]} must export ${symbol} (imported by ${path.basename(source)})`);
        checked += 1;
      }
    }
  }
  assert.ok(checked >= 15, `expected to verify several imports, got ${checked}`);
});
